// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void StartIEandAddToCart()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchusinEdit = this.UINewtabInternetExplorWindow.UIAddressBarClient.UIAddressandsearchusinEdit;
            WinEdit uIItemEdit = this.UINewtabInternetExplorWindow.UIItemWindow.UIItemEdit;
            BrowserWindow uINewtabInternetExplorWindow = this.UINewtabInternetExplorWindow;
            HtmlImage uIKnockoutjsBuildingDyImage = this.UINewtabInternetExplorWindow.UIHomePageMyASPNETApplDocument.UIKnockoutjsBuildingDyImage;
            HtmlButton uIAddToCartButton = this.UINewtabInternetExplorWindow.UIKnockoutjsBuildingDyDocument.UIBookDetailsPane.UIAddToCartButton;
            #endregion

            // Go to web page 'about:Tabs' using new browser instance
            this.UINewtabInternetExplorWindow.LaunchUrl(new System.Uri(this.RecordedMethod1Params.UINewtabInternetExplorWindowUrl));

            // Click 'Address and search using Bing' text box
            Mouse.Click(uIAddressandsearchusinEdit, new Point(613, 6));

            // Type 'Control + v' in text box
            //Keyboard.SendKeys(uIItemEdit, this.RecordedMethod1Params.UIItemEditSendKeys, ModifierKeys.Control);

            // Type '{Down}' in text box
            //Keyboard.SendKeys(uIItemEdit, this.RecordedMethod1Params.UIItemEditSendKeys1, ModifierKeys.None);

            // Go to web page 'http://shoppingcarttest.azurewebsites.net/'
            uINewtabInternetExplorWindow.NavigateToUrl(new System.Uri(this.RecordedMethod1Params.UINewtabInternetExplorWindowUrl1));

            // Click 'Knockout.js: Building Dynamic Client-Side Web Appl...' image
            Mouse.Click(uIKnockoutjsBuildingDyImage, new Point(14, 186));

            // Click 'Knockout.js: Building Dynamic Client-Side Web Appl...' image
            Mouse.Click(uIKnockoutjsBuildingDyImage, new Point(87, 144));

            // Click 'Add To Cart' button
            Mouse.Click(uIAddToCartButton, new Point(78, 29));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UINewtabInternetExplorWindow UINewtabInternetExplorWindow
        {
            get
            {
                if ((this.mUINewtabInternetExplorWindow == null))
                {
                    this.mUINewtabInternetExplorWindow = new UINewtabInternetExplorWindow();
                }
                return this.mUINewtabInternetExplorWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UINewtabInternetExplorWindow mUINewtabInternetExplorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'about:Tabs' using new browser instance
        /// </summary>
        public string UINewtabInternetExplorWindowUrl = "about:Tabs";
        
        /// <summary>
        /// Type 'Control + v' in text box
        /// </summary>
        public string UIItemEditSendKeys = "v";
        
        /// <summary>
        /// Type '{Down}' in text box
        /// </summary>
        public string UIItemEditSendKeys1 = "{Down}";
        
        /// <summary>
        /// Go to web page 'http://shoppingcarttest.azurewebsites.net/'
        /// </summary>
        public string UINewtabInternetExplorWindowUrl1 = "http://shoppingcarttest.azurewebsites.net/";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINewtabInternetExplorWindow : BrowserWindow
    {
        
        public UINewtabInternetExplorWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "New tab";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("New tab");
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            this.WindowTitles.Add("Knockout.js: Building Dynamic Client-Side Web Applications - My ASP.NET Applicati" +
                    "on");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIHomePageMyASPNETApplDocument UIHomePageMyASPNETApplDocument
        {
            get
            {
                if ((this.mUIHomePageMyASPNETApplDocument == null))
                {
                    this.mUIHomePageMyASPNETApplDocument = new UIHomePageMyASPNETApplDocument(this);
                }
                return this.mUIHomePageMyASPNETApplDocument;
            }
        }
        
        public UIKnockoutjsBuildingDyDocument UIKnockoutjsBuildingDyDocument
        {
            get
            {
                if ((this.mUIKnockoutjsBuildingDyDocument == null))
                {
                    this.mUIKnockoutjsBuildingDyDocument = new UIKnockoutjsBuildingDyDocument(this);
                }
                return this.mUIKnockoutjsBuildingDyDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressBarClient mUIAddressBarClient;
        
        private UIItemWindow mUIItemWindow;
        
        private UIHomePageMyASPNETApplDocument mUIHomePageMyASPNETApplDocument;
        
        private UIKnockoutjsBuildingDyDocument mUIKnockoutjsBuildingDyDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("New tab");
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("New tab");
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("Home Page - My ASP.NET Application");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Address and search using Bing";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Edit";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageMyASPNETApplDocument : HtmlDocument
    {
        
        public UIHomePageMyASPNETApplDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://shoppingcarttest.azurewebsites.net/";
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIKnockoutjsBuildingDyImage
        {
            get
            {
                if ((this.mUIKnockoutjsBuildingDyImage == null))
                {
                    this.mUIKnockoutjsBuildingDyImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIKnockoutjsBuildingDyImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIKnockoutjsBuildingDyImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIKnockoutjsBuildingDyImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Knockout.js: Building Dynamic Client-Side Web Applications";
                    this.mUIKnockoutjsBuildingDyImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/images/I/51T%2BWt430bL._AA160_.jpg";
                    this.mUIKnockoutjsBuildingDyImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://ecx.images-amazon.com/images/I/51T%2BWt430bL._AA160_.jpg";
                    this.mUIKnockoutjsBuildingDyImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/Books/Details/1";
                    this.mUIKnockoutjsBuildingDyImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://shoppingcarttest.azurewebsites.net/Books/Details/1";
                    this.mUIKnockoutjsBuildingDyImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIKnockoutjsBuildingDyImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "title=\"Knockout.js: Building Dynamic Cli";
                    this.mUIKnockoutjsBuildingDyImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIKnockoutjsBuildingDyImage.WindowTitles.Add("Home Page - My ASP.NET Application");
                    #endregion
                }
                return this.mUIKnockoutjsBuildingDyImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIKnockoutjsBuildingDyImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIKnockoutjsBuildingDyDocument : HtmlDocument
    {
        
        public UIKnockoutjsBuildingDyDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Knockout.js: Building Dynamic Client-Side Web Applications - My ASP.NET Applicati" +
                "on";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Books/Details/1";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://shoppingcarttest.azurewebsites.net/Books/Details/1";
            this.WindowTitles.Add("Knockout.js: Building Dynamic Client-Side Web Applications - My ASP.NET Applicati" +
                    "on");
            #endregion
        }
        
        #region Properties
        public UIBookDetailsPane UIBookDetailsPane
        {
            get
            {
                if ((this.mUIBookDetailsPane == null))
                {
                    this.mUIBookDetailsPane = new UIBookDetailsPane(this);
                }
                return this.mUIBookDetailsPane;
            }
        }
        #endregion
        
        #region Fields
        private UIBookDetailsPane mUIBookDetailsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIBookDetailsPane : HtmlDiv
    {
        
        public UIBookDetailsPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "bookDetails";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Jamie Munro\r\n\r\nYour Price: $17.99\r\n\r\nLis";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "row";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"row\" id=\"bookDetails\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "12";
            this.WindowTitles.Add("Knockout.js: Building Dynamic Client-Side Web Applications - My ASP.NET Applicati" +
                    "on");
            #endregion
        }
        
        #region Properties
        public HtmlButton UIAddToCartButton
        {
            get
            {
                if ((this.mUIAddToCartButton == null))
                {
                    this.mUIAddToCartButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIAddToCartButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIAddToCartButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAddToCartButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Add To Cart";
                    this.mUIAddToCartButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAddToCartButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAddToCartButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUIAddToCartButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\" type=\"submit\" da";
                    this.mUIAddToCartButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIAddToCartButton.WindowTitles.Add("Knockout.js: Building Dynamic Client-Side Web Applications - My ASP.NET Applicati" +
                            "on");
                    #endregion
                }
                return this.mUIAddToCartButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUIAddToCartButton;
        #endregion
    }
}
